# Generated by Django 5.2.1 on 2025-05-13 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(help_text="User's role in the system", on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
