# Generated by Django 5.2.1 on 2025-05-14 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': ['TA']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties', to=settings.AUTH_USER_MODEL),
        ),
    ]
