# Generated by Django 5.2.1 on 2025-05-13 13:31

import django.db.models.deletion
import django.utils.timezone
import student_submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
        ('student_submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submission_timestamp']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_content',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to=student_submissions.models.submission_upload_path, verbose_name='Submission File'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='duties.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Grading Comments'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__name', 'Faculty'), ('role__name', 'TA'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Initial Submission'), ('RESUBMISSION', 'Resubmission'), ('LATE', 'Late Submission'), ('DRAFT', 'Draft')], default='INITIAL', max_length=50),
        ),
    ]
