# Generated by Django 5.2.1 on 2025-05-13 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_submissions', '0002_alter_submission_options_remove_submission_file_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grading_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
