# Generated by Django 5.2.1 on 2025-05-13 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assignments', '0003_alter_tacourseassignment_ta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacourseassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tacourseassignment',
            name='ta',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_ta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='ta',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_faculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
