# Generated by Django 5.2.1 on 2025-05-13 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('ta_assignments', '0004_alter_tacourseassignment_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tacourseassignment',
            options={'verbose_name': 'TA Course Assignment', 'verbose_name_plural': 'TA Course Assignments'},
        ),
        migrations.AlterModelOptions(
            name='tafacultyassignment',
            options={'verbose_name': 'TA Faculty Assignment', 'verbose_name_plural': 'TA Faculty Assignments'},
        ),
        migrations.AlterField(
            model_name='tacourseassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by (Admin)'),
        ),
        migrations.AlterField(
            model_name='tacourseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_assignments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='tacourseassignment',
            name='ta',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_course_assignments', to=settings.AUTH_USER_MODEL, verbose_name='TA (Student)'),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by (Admin)'),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tas_to_faculty', to=settings.AUTH_USER_MODEL, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='ta',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_faculty_assignments', to=settings.AUTH_USER_MODEL, verbose_name='TA (Student)'),
        ),
    ]
