# Generated by Django 5.2.1 on 2025-05-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assignments', '0005_alter_tacourseassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacourseassignment',
            name='ta',
            field=models.ForeignKey(limit_choices_to={'role__name': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_course_assignments', to=settings.AUTH_USER_MODEL, verbose_name='TA (Student)'),
        ),
        migrations.AlterField(
            model_name='tafacultyassignment',
            name='ta',
            field=models.ForeignKey(limit_choices_to={'role__name': 'TA'}, on_delete=django.db.models.deletion.CASCADE, related_name='ta_faculty_assignments', to=settings.AUTH_USER_MODEL, verbose_name='TA (Student)'),
        ),
    ]
