# Generated by Django 5.2.1 on 2025-05-15 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assignments', '0006_alter_tacourseassignment_ta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tafacultyassignment',
            unique_together={('ta', 'faculty')},
        ),
    ]
