# Generated by Django 5.2.1 on 2025-05-15 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('ta_assignments', '0007_alter_tafacultyassignment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tacourseassignment',
            unique_together={('ta', 'course')},
        ),
    ]
