# Generated by Django 5.2.1 on 2025-05-15 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assignments', '0008_alter_tacourseassignment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacourseassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name_in': ('Admin', 'Faculty')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by (Admin)'),
        ),
    ]
