# Generated by Django 5.2.1 on 2025-05-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duties', '0003_alter_assignment_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('NOT_COMPLETED', 'Not Completed')], default='COMPLETED', help_text='The completion status of the duty.', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='duties.assignment')),
                ('fulfilled_by', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'TA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties_fulfilled_logs', to=settings.AUTH_USER_MODEL, verbose_name='Fulfilled By (TA)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties_updated_logs', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['-completion_timestamp'],
                'unique_together': {('duty', 'fulfilled_by')},
            },
        ),
    ]
