# Generated by Django 5.2.1 on 2025-05-11 09:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_assignment_is_completed'),
        ('duty_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutycompletionlog',
            options={'ordering': ['-completion_timestamp'], 'verbose_name': 'Duty Completion Log', 'verbose_name_plural': 'Duty Completion Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='dutycompletionlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dutycompletionlog',
            name='completed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Student', 'TA']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties_completed_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutycompletionlog',
            name='duty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_log', to='duties.assignment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dutycompletionlog',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='dutycompletionlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dutycompletionlog',
            name='ta',
        ),
    ]
