# Generated by Django 5.2.1 on 2025-05-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_assignment_is_completed'),
        ('duty_tracking', '0002_alter_dutycompletionlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutycompletionlog',
            name='duty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_log', to='duties.assignment'),
        ),
    ]
