# Generated by Django 5.2.1 on 2025-05-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_assignment_is_completed'),
        ('duty_tracking', '0003_alter_dutycompletionlog_duty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutycompletionlog',
            name='completed_by',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['Student', 'TA']}, on_delete=django.db.models.deletion.CASCADE, related_name='duties_completed_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dutycompletionlog',
            name='duty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_log', to='duties.assignment'),
        ),
    ]
