# Generated by Django 5.2.1 on 2025-05-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_assignment_is_completed'),
        ('duty_tracking', '0004_alter_dutycompletionlog_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dutycompletionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('NOT_COMPLETED', 'Not Completed')], default='COMPLETED', help_text='The completion status of the duty.', max_length=50),
        ),
        migrations.AlterField(
            model_name='dutycompletionlog',
            name='completed_by',
            field=models.ForeignKey(limit_choices_to={'role__role_name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='duties_completed_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dutycompletionlog',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='duties.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='dutycompletionlog',
            unique_together={('duty', 'completed_by')},
        ),
    ]
